# Generated by Django 4.2.6 on 2023-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceramica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('descipcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='ceramicas/')),
            ],
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('descipcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='cuadros/')),
            ],
        ),
        migrations.CreateModel(
            name='Escultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('descipcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='esculturas/')),
            ],
        ),
    ]
